version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: main
  labels:
  - automerge
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: nunomaduro/collision
    versions:
    - 5.4.0
  - dependency-name: symfony/string
    versions:
    - 5.2.6
  - dependency-name: symfony/console
    versions:
    - 5.2.5
    - 5.2.6
  - dependency-name: filp/whoops
    versions:
    - 2.11.0
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-intl-grapheme
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-mbstring
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
